[project]
name = "myapp"
version = "0.1.0"
description = "My test app"
requires-python = ">=3.11"

[tool.uv]
python-preference = "managed"

[tool.uv.dependency-groups]
default = [
    "requests*",
    "pandas*"
]

dev = [
    "pytest*"
]

